const authTranslation = {
  en: {
    // SMS Verification
    enterSmsCode: "Enter Code",
    sixDigitCode: "6-digit code",
    enterSixDigitCode: "Enter 6-digit code",
    verify: "Verify",
    verifying: "Verifying...",

    // Login Form
    welcomeBack: "Welcome Back",
    loginSubtitle: "Login to your VLSystem account",
    username: "Username",
    password: "Password",
    show: "Show",
    hide: "Hide",
    forgotPrompt: "Forgot Password or Username?",
    loggingIn: "Logging in...",
    login: "Login",

    // Profile Upload
    onlyJpegPng: "Only JPEG or PNG allowed for profile picture.",
    userNotAuthenticated: "User not authenticated",
    uploadFailed: "Upload failed",
    removeFailed: "Remove failed",

    // Collection Functions
    noTableFound: "No table found to print.",
    unableToOpenPrint: "Unable to open print window.",
    paymentFailed: "Payment failed.",
    failedToSaveNote: "Failed to save note.",
    collectionsReport: "Collections Report",
    summary: "Summary",
    recordsPrinted: "records printed on",
    generatedBy: "Generated by Vistula Lending System • Confidential Report",

    // User Management
    createNewUser: "Create New User",
    createNewUserSubtitle: "Fill out the details below to add a new team member.",
    enterName: "Enter Name",
    enterEmail: "Enter Email",
    enterPhoneNumber: "Enter Phone Number",
    roleHead: "Head",
    roleManager: "Manager",
    roleLoanOfficer: "Loan Officer",
    roleCollector: "Collector",
    cancel: "Cancel",
    createUser: "Create User",
    confirmCreateUser: "Are you sure you want to create this user?",
    users: "Users",

    // Error Modal
    error: "Error",
    agentSelectionError: "Agent Selection Error",
    missingFieldsError: "Missing Fields Error",
    documentUploadError: "Document Upload Error",
    documentUploadIssue: "Document Upload Issue",
    close: "Close",
  },
  ceb: {
    // SMS Verification
    enterSmsCode: "Isulod ang Code",
    sixDigitCode: "6-ka digit nga code",
    enterSixDigitCode: "Isulod ang 6-ka digit nga code",
    verify: "I-verify",
    verifying: "Gina-verify...",

    // Login Form
    welcomeBack: "Maayong Pagbalik",
    loginSubtitle: "Sulod sa imong VLSystem account",
    username: "Username",
    password: "Password",
    show: "Ipakita",
    hide: "Tagoa",
    forgotPrompt: "Nakalimot sa Password o Username?",
    loggingIn: "Nag-log in...",
    login: "Sulod",

    // Profile Upload
    onlyJpegPng: "JPEG o PNG lang ang gitugotan para sa profile picture.",
    userNotAuthenticated: "Dili awtorisado ang user",
    uploadFailed: "Napakyas ang pag-upload",
    removeFailed: "Napakyas ang pagtangtang",

    // Collection Functions
    noTableFound: "Walay nakit-ang table para sa pag-print.",
    unableToOpenPrint: "Dili maabli ang print window.",
    paymentFailed: "Napakyas ang bayad.",
    failedToSaveNote: "Napakyas sa pag-save sa note.",
    collectionsReport: "Report sa Koleksyon",
    summary: "Sumaryo",
    recordsPrinted: "mga rekord nga na-print sa",
    generatedBy: "Gihimo sa Vistula Lending System • Konpidensyal nga Report",

    // User Management
    createNewUser: "Paghimo ug Bag-ong User",
    createNewUserSubtitle: "Puno-a ang mga detalye sa ubos aron makadugang ug bag-ong miyembro sa team.",
    enterName: "Isulod ang Ngalan",
    enterEmail: "Isulod ang Email",
    enterPhoneNumber: "Isulod ang Numero sa Telepono",
    roleHead: "Head",
    roleManager: "Manager",
    roleLoanOfficer: "Loan Officer",
    roleCollector: "Collector",
    cancel: "I-cancel",
    createUser: "Paghimo ug User",
    confirmCreateUser: "Sigurado ka nga gusto nimo himoon kini nga user?",
    users: "Mga User",

    // Error Modal
    error: "Sayop",
    agentSelectionError: "Sayop sa Pagpili sa Agent",
    missingFieldsError: "Sayop sa Kulang nga mga Field",
    documentUploadError: "Sayop sa Pag-upload sa Dokumento",
    documentUploadIssue: "Problema sa Pag-upload sa Dokumento",
    close: "Sirad-a",
  }
};

export default authTranslation;
