import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Configure Geist Sans font with CSS variable
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Configure Geist Mono font with CSS variable
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Application metadata configuration
export const metadata: Metadata = {
  title: "VLSystem", 
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/logo/vis.ico", type: "image/x-icon" }
    ],
    shortcut: "/logo/vis.ico",
  },
};

/**
 * Root layout component that wraps the entire application
 * Provides font configuration and basic HTML structure
 * @param children - React components to be rendered inside the layout
 * @returns JSX element with HTML structure and font classes
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
