import { Collection } from "../utils/Types/collection";

const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL

// Printing Sheet
export const handlePrint = (setPrintMode: (v: boolean) => void) => {
  setPrintMode(true);

  setTimeout(() => {
    const table = document.querySelector("table");
    if (!table) {
      alert("No table found to print.");
      setPrintMode(false);
      return;
    }

    const printWindow = window.open("", "_blank");
    if (!printWindow) {
      alert("Unable to open print window.");
      setPrintMode(false);
      return;
    }

    const today = new Date().toLocaleDateString("en-PH", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    printWindow.document.write(`
      <html>
        <head>
          <title>Collections Report - ${today}</title>
          <style>
            @page {
              margin: 20mm;
            }

            body {
              font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
              margin: 0;
              padding: 0;
              background: #fff;
              color: #333;
            }

            .header {
              text-align: center;
              margin-bottom: 40px;
              border-bottom: 2px solid #b91c1c;
              padding-bottom: 10px;
            }

            .company-name {
              font-size: 22px;
              font-weight: 700;
              color: #b91c1c;
              margin-bottom: 5px;
            }

            .report-title {
              font-size: 18px;
              font-weight: 600;
              color: #111827;
              margin-bottom: 3px;
            }

            .report-date {
              font-size: 14px;
              color: #6b7280;
            }

            table {
              border-collapse: collapse;
              width: 100%;
              margin-top: 20px;
              font-size: 14px;
              border-radius: 8px;
              overflow: hidden;
              box-shadow: 0 0 6px rgba(0,0,0,0.08);
            }

            th {
              background: linear-gradient(to bottom, #ef4444, #dc2626);
              color: white;
              font-weight: 600;
              text-align: left;
              padding: 12px 10px;
            }

            td {
              border-bottom: 1px solid #e5e7eb;
              padding: 10px 8px;
              text-align: left;
              vertical-align: middle;
            }

            tr:nth-child(even) td {
              background-color: #f9fafb;
            }

            tr:hover td {
              background-color: #f3f4f6;
            }

            td.amount {
              text-align: right;
              font-variant-numeric: tabular-nums;
            }

            tfoot td {
              font-weight: bold;
              border-top: 2px solid #b91c1c;
              background-color: #fef2f2;
              color: #991b1b;
            }

            /* Hide Actions column when printing */
            th:last-child,
            td:last-child {
              display: none;
            }

            .summary-box {
              margin-top: 25px;
              padding: 15px;
              background: #fef2f2;
              border-left: 4px solid #b91c1c;
              border-radius: 6px;
              font-size: 14px;
              width: fit-content;
            }

            .footer {
              text-align: center;
              margin-top: 40px;
              font-size: 12px;
              color: #9ca3af;
            }
          </style>
        </head>
        <body>
          <div class="header">
            <div class="company-name">Vistula Lending Corporation</div>
            <div class="report-title">Collections Report</div>
            <div class="report-date">${today}</div>
          </div>

          ${table.outerHTML}

          <div class="summary-box">
            Summary: ${table.querySelectorAll("tr").length - 1} records printed on ${today}.
          </div>

          <div class="footer">
            Generated by Vistula Lending System • Confidential Report
          </div>
        </body>
      </html>
    `);

    printWindow.document.close();
    printWindow.focus();
    printWindow.print();
    printWindow.close();

    setPrintMode(false);
  }, 200);
};

// Open Payment Modal
export const handleMakePayment = (
  collection: Collection,
  setSelectedCollection: (col: Collection | null) => void,
  setPaymentAmount: (amount: number) => void,
  setShowModal: (v: boolean) => void
) => {
  setSelectedCollection(collection);
  setPaymentAmount(collection.periodAmount - collection.paidAmount);
  setShowModal(true);
};

// Open Note Modal
export const handleAddNote = (
  collection: Collection,
  setSelectedCollection: (col: Collection | null) => void,
  setNoteText: (text: string) => void,
  setShowNoteModal: (v: boolean) => void
) => {
  setSelectedCollection(collection);
  setNoteText(collection.note || "");
  setShowNoteModal(true);
};

// Close Payment Modal
export const handlePaymentModalClose = (
  setIsPaymentModalAnimating: (v: boolean) => void,
  setShowModal: (v: boolean) => void,
  setIsPaymentModalVisible: (v: boolean) => void,
  setSelectedCollection: (col: Collection | null) => void,
  setPaymentAmount: (amount: number) => void
) => {
  setIsPaymentModalAnimating(false);
  setTimeout(() => {
    setShowModal(false);
    setIsPaymentModalVisible(false);
    setSelectedCollection(null);
    setPaymentAmount(0);
  }, 150);
};

// Close Note Modal
export const handleNoteModalClose = (
  setIsNoteModalAnimating: (v: boolean) => void,
  setShowNoteModal: (v: boolean) => void,
  setIsNoteModalVisible: (v: boolean) => void,
  setSelectedCollection: (col: Collection | null) => void,
  setNoteText: (text: string) => void
) => {
  setIsNoteModalAnimating(false);
  setTimeout(() => {
    setShowNoteModal(false);
    setIsNoteModalVisible(false);
    setSelectedCollection(null);
    setNoteText("");
  }, 150);
};

// Confirm Payment
export const handleConfirmPayment = async (
  selectedCollection: Collection | null,
  paymentAmount: number,
  setCollections: (cb: (prev: Collection[]) => Collection[]) => void,
  setPaymentLoading: (v: boolean) => void,
  setShowPaymentConfirm: (v: boolean) => void,
  setErrorMsg: (msg: string) => void,
  setShowErrorModal: (v: boolean) => void,
  handleClose: () => void,
  setShowReceiptModal?: (v: boolean) => void,
  setReceiptData?: (data: any) => void
) => {
  if (!selectedCollection) return;
  setPaymentLoading(true);

  try {
    const token = localStorage.getItem("token"); 
    if (!token) throw new Error("No token found"); 

    const collectorName = localStorage.getItem("collectorName") || "Collector";

    const response = await fetch(
      `${BASE_URL}/payments/${selectedCollection.referenceNumber}/cash`,
      {
        method: "POST",
       headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${token}`, 
      },
        body: JSON.stringify({ amount: paymentAmount }),
      }
    );

    if (!response.ok) throw new Error("Failed to post payment");

    const result = await response.json();
    
    // Update collections list with new status and paid amount
    const updatedCollection: Collection = result;
    setCollections((prev) =>
      prev.map((col) => {
        if (col.referenceNumber === updatedCollection.referenceNumber) {
          // Update the collection with new data, but preserve the decrypted name
          return {
            ...col,
            status: updatedCollection.status,
            paidAmount: updatedCollection.paidAmount,
            periodBalance: updatedCollection.periodBalance,
            loanBalance: updatedCollection.loanBalance || col.loanBalance,
            periodAmount: updatedCollection.periodAmount || col.periodAmount
          };
        }
        return col;
      })
    );

    // Payment successful - stop loading and close modals
    setPaymentLoading(false);
    
    // Close confirm payment modal
    setShowPaymentConfirm(false);
    
    // Wait for confirm modal to close, then close main payment modal
    setTimeout(() => {
      handleClose();
      
      // Show receipt modal after both modals are closed
      if (setShowReceiptModal && setReceiptData && result.paymentLogs && result.paymentLogs.length > 0) {
        setTimeout(() => {
          const paymentLog = result.paymentLogs[0];
          setReceiptData({
            referenceNumber: paymentLog.referenceNumber,
            amount: paymentLog.amount,
            datePaid: paymentLog.datePaid,
            loanId: paymentLog.loanId,
            borrowersId: paymentLog.borrowersId,
            collector: collectorName,
            mode: paymentLog.mode || 'Cash',
            paidToCollection: paymentLog.paidToCollection,
            borrowerName: selectedCollection.name,
          });
          setShowReceiptModal(true);
        }, 300);
      }
    }, 200);
  } catch (err) {
    console.error("Payment failed:", err);
    setPaymentLoading(false);
    setErrorMsg("Payment failed.");
    setShowErrorModal(true);
    setShowPaymentConfirm(false);
    handleClose();
  }
};

// Save Note
export const handleSaveNote = async (
  selectedCollection: Collection | null,
  noteText: string,
  setCollections: (cb: (prev: Collection[]) => Collection[]) => void,
  setErrorMsg: (msg: string) => void,
  setShowErrorModal: (v: boolean) => void,
  setNoteLoading: (v: boolean) => void,
  setSuccessMessage: (msg: string) => void,
  setShowSuccessModal: (v: boolean) => void,
  handleClose: () => void
) => {
  if (!selectedCollection) return;

  setNoteLoading(true);

  try {
    const token = localStorage.getItem("token");
    const response = await fetch(
      `${BASE_URL}/collections/${selectedCollection.referenceNumber}/note`,
      {
        method: "PUT",
        headers: { 
          "Content-Type": "application/json",
          "Authorization": `Bearer ${token}`
        },
        body: JSON.stringify({ note: noteText }),
      }
    );

    const responseText = await response.text();
    console.log("Note save response:", responseText);

    if (!response.ok) {
      let errorMsg = "Failed to save note";
      try {
        const errorData = JSON.parse(responseText);
        errorMsg = errorData.error || errorMsg;
      } catch (e) {
        errorMsg = responseText || errorMsg;
      }
      throw new Error(errorMsg);
    }

    const updatedCollection: Collection = JSON.parse(responseText);

    setCollections((prev) =>
      prev.map((col) =>
        col.referenceNumber === updatedCollection.referenceNumber
          ? { ...col, note: updatedCollection.note }
          : col
      )
    );
    
    setNoteLoading(false);
    handleClose();
    
    // Show success modal
    setSuccessMessage("Note saved successfully!");
    setShowSuccessModal(true);
  } catch (err: any) {
    console.error("Saving note failed:", err);
    setNoteLoading(false);
    setErrorMsg(err.message || "Failed to save note.");
    setShowErrorModal(true);
  }
};
